### PR TITLE
Binops should not get parenthesis around them when used in series.

### PR DESCRIPTION
**Pull request by mindreader**
When you do.
```haskell
rel1 `unionAll` rel2 `unionAll` rel3
```
You end up with a query like:
```SQL
(select * from t1 union all select * from t2) union all select * from t3
```
Which is invalid in mysql due to the parenthesis.  It may also be invalid in postgresql, but I don't have a db on hand to check.

Let me know if you want me to do something differently, I'll be happy to fix it.

### CODE REVIEW

**Comment by khibino** [comment]
I can't accept this change.
When using `union', `intersect' and `except' operators together,
associativite law is not formd for this binary operators.

＞ Which is invalid in mysql due to the parenthesis. It may also be invalid in postgresql, but I don't have a db on hand to check.

PostgreSQL does not have this problem.
PostgreSQL supports `intersect' and `except' operators other than `union' operator.

**Comment by khibino** [comment]
Any better ideas?

**Comment by mindreader** [comment]
Sqlite also suffers from this.  Also neither mysql or sqlite have intersect or except.  It might be possible to make a separate set of operators for them?

It might also be possible to make successive unions not use parenthesis, but then insert parenthesis on subsequence intersects / excepts.

**Comment by khibino** [comment]
You may wrap with select to avoid this problem.

```Haskell
relation (query $ rel1 `unionAll` rel2) `unionAll` rel3
```

**Comment by mindreader** [comment]
Thanks.  That's something.

**Pull request closed without merging**
