### PR TITLE
identifier quotation

### PR DESCRIPTION
**Pull request by kakkun61**
# Why?

I want to use identifiers which are keywords or which have signs. So I need to quote identifiers.

# Features

- [x] Configuration about identifier quotation (quoting or not, which character to use)
- Quoting identifiers
  - [x] schema and table
  - [x] column
- [x] Escaping

### CODE REVIEW

**Comment by kakkun61** [comment]
@khibino Is this approach good?

**Comment by kakkun61** [comment]
When HRR configuration and a table is following

```haskell
Database.Relational.Schema.MySQLInfo.Config.config { identifierQuotation = Quotation '`' }
```

```sql
CREATE TABLE `fruit"``` (
  `id"``` int(11) NOT NULL,
  `name` varchar(10) NOT NULL,
  `price` int(11) NOT NULL,
  PRIMARY KEY (`id"```)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

and then `$(defineTable "fruit\"`")` is following (ghc -dump-splices).

```haskell
    data Fruit
      = Fruit {id :: !GHC.Int.Int32,
               name :: !String,
               price :: !GHC.Int.Int32}
      deriving (Show)
    columnOffsetsFruit :: GHC.Arr.Array Int Int
    columnOffsetsFruit
      = ((GHC.Arr.listArray (0 :: Int, 3))
         $ (scanl
              (+)
              (0 :: Int)
              [Database.Record.Persistable.runPersistableRecordWidth
                 (Database.Record.Persistable.persistableWidth ::
                    Database.Record.Persistable.PersistableRecordWidth GHC.Int.Int32),
               Database.Record.Persistable.runPersistableRecordWidth
                 (Database.Record.Persistable.persistableWidth ::
                    Database.Record.Persistable.PersistableRecordWidth String),
               Database.Record.Persistable.runPersistableRecordWidth
                 (Database.Record.Persistable.persistableWidth ::
                    Database.Record.Persistable.PersistableRecordWidth GHC.Int.Int32)]))
    instance Database.Record.Persistable.PersistableWidth Fruit where
      Database.Record.Persistable.persistableWidth
        = (Database.Record.Persistable.unsafePersistableRecordWidth
           $ (columnOffsetsFruit GHC.Arr.! 3))
    instance Database.Relational.Query.Pure.ProductConstructor (GHC.Int.Int32
                                                                -> String
                                                                   -> GHC.Int.Int32 -> Fruit) where
      Database.Relational.Query.Pure.productConstructor = Fruit
    instance Database.Relational.Query.Table.TableDerivable Fruit where
      Database.Relational.Query.Table.derivedTable
        = Database.Relational.Query.Table.table
            "`tutorial`.`fruit\"```" ["`id\"```", "`name`", "`price`"]
    tableOfFruit :: Database.Relational.Query.Table.Table Fruit
    tableOfFruit = Database.Relational.Query.Table.derivedTable
    fruit :: Database.Relational.Query.Monad.BaseType.Relation () Fruit
    fruit = Database.Relational.Query.Relation.derivedRelation
    insertFruit :: Database.Relational.Query.Type.Insert Fruit
    insertFruit
      = Database.Relational.Query.Type.derivedInsert
          Database.Relational.Query.Pi.id'
    insertQueryFruit ::
      forall p_a6pH.
      Database.Relational.Query.Monad.BaseType.Relation p_a6pH Fruit
      -> Database.Relational.Query.Type.InsertQuery p_a6pH
    insertQueryFruit
      = Database.Relational.Query.Type.derivedInsertQuery
          Database.Relational.Query.Pi.id'
    id' :: Database.Relational.Query.Pi.Unsafe.Pi Fruit GHC.Int.Int32
    id'
      = Database.Relational.Query.Pi.Unsafe.definePi
          (columnOffsetsFruit Data.Array.Base.! 0)
    name' :: Database.Relational.Query.Pi.Unsafe.Pi Fruit String
    name'
      = Database.Relational.Query.Pi.Unsafe.definePi
          (columnOffsetsFruit Data.Array.Base.! 1)
    price' ::
      Database.Relational.Query.Pi.Unsafe.Pi Fruit GHC.Int.Int32
    price'
      = Database.Relational.Query.Pi.Unsafe.definePi
          (columnOffsetsFruit Data.Array.Base.! 2)
    instance Database.Record.KeyConstraint.HasColumnConstraint Database.Record.KeyConstraint.Primary Fruit where
      Database.Record.KeyConstraint.columnConstraint
        = Database.Record.KeyConstraint.unsafeSpecifyColumnConstraint 0
    instance Database.Record.KeyConstraint.HasKeyConstraint Database.Record.KeyConstraint.Primary Fruit where
      Database.Record.KeyConstraint.keyConstraint
        = Database.Record.KeyConstraint.derivedCompositePrimary
    instance Database.Relational.Query.Constraint.HasConstraintKey Database.Record.KeyConstraint.Primary Fruit GHC$Int.Int32 where
      Database.Relational.Query.Constraint.constraintKey
        = Database.Relational.Query.Constraint.unsafeDefineConstraintKey
            [0]
    selectFruit ::
      Database.Relational.Query.Type.Query GHC.Int.Int32 Fruit
    selectFruit
      = Database.Relational.Query.Type.relationalQuery
          (Database.Relational.Query.Derives.primary fruit)
    updateFruit ::
      Database.Relational.Query.Type.KeyUpdate GHC.Int.Int32 Fruit
    updateFruit
      = Database.Relational.Query.Derives.primaryUpdate tableOfFruit
    instance Database.Record.KeyConstraint.HasColumnConstraint Database.Record.KeyConstraint.NotNull Fruit where
      Database.Record.KeyConstraint.columnConstraint
        = Database.Record.KeyConstraint.unsafeSpecifyColumnConstraint 0
    fromSqlOfFruit ::
      Database.Record.FromSql.RecordFromSql Database.HDBC.SqlValue.SqlValue Fruit
    fromSqlOfFruit
      = ((((pure Fruit) <*> Database.Record.FromSql.recordFromSql)
          <*> Database.Record.FromSql.recordFromSql)
         <*> Database.Record.FromSql.recordFromSql)
    toSqlOfFruit ::
      Database.Record.ToSql.RecordToSql Database.HDBC.SqlValue.SqlValue Fruit
    toSqlOfFruit
      = Database.Record.ToSql.wrapToSql
          (\ (Fruit f1_a6pI f2_a6pJ f3_a6pK)
             -> ((Database.Record.ToSql.putRecord f1_a6pI)
                 >>
                   ((Database.Record.ToSql.putRecord f2_a6pJ)
                    >>
                      ((Database.Record.ToSql.putRecord f3_a6pK)
                       >> (Database.Record.ToSql.putEmpty GHC.Tuple.())))))
    instance Database.Record.FromSql.FromSql Database.HDBC.SqlValue.SqlValue Fruit where
      Database.Record.FromSql.recordFromSql = fromSqlOfFruit
    instance Database.Record.ToSql.ToSql Database.HDBC.SqlValue.SqlValue Fruit where
      Database.Record.ToSql.recordToSql = toSqlOfFruit
```

**Comment by kakkun61** [comment]
When there are “Fruit” table and “Fruit`” table, something bad may happen.

**Comment by khibino** [comment]
Merged thanks!

**Pull request merged**
