### PR TITLE
Added .gitignore.

### PR DESCRIPTION
**Pull request by cdepillabout**
Added [.gitignore for Haskell projects](https://github.com/github/gitignore/blob/master/Haskell.gitignore).

This makes the output of `git status` a little bit cleaner when using sandboxes.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I can accept this.

@khibino @yuga What do you think?

**Comment by yuga** [comment]
I think that the entries for cabal-dev and hsenv should be placed in global .gitignore because they are developer's private tools as emacs and vim. Well, I often add *.swp in my repository too, but It is useful to only vim user:)

Anyway, I can accept it if it is practice in Haskell community.

**Comment by khibino** [comment]
I can accept this too. Is it better method to add a download script than to add this directly?

**Comment by cdepillabout** [comment]
> I think that the entries for cabal-dev and hsenv should be placed in global .gitignore because they are developer's private tools as emacs and vim.

I agree with you that these things could definitely be placed in a developer's global gitignore.  I've checked in a couple popular Haskell packages to see if they include a gitignore or not:

- [pandoc](https://github.com/jgm/pandoc/blob/master/.gitignore) -- has .gitignore, ignores things like cabal-dev and cabal sandboxes, also ignores emacs(?) swap files
- [yesod](https://github.com/yesodweb/yesod/blob/master/.gitignore) -- has .gitignore, ignores things like cabal-dev and cabal sandboxes, also ignores emacs(?) swap files
- [fay](https://github.com/faylang/fay/blob/master/.gitignore) -- has .gitignore, ignores things like cabal-dev and cabal sandboxes.  does NOT ignore emacs or vim swap files
- [semigroups (and other ekmett repos)](https://github.com/ekmett/semigroups/blob/master/.gitignore) -- has .gitignore, ignores cabal sandboxes (but not cabal-dev).  also ignores emacs and vim swap files
- [cabal](https://github.com/haskell/cabal/blob/master/.gitignore) -- has .gitignore, ignores things like cabal-dev and cabal sandboxes. also ignores emacs and vim swap files
- [hledger](https://github.com/simonmichael/hledger/blob/master/.gitignore) -- has .gitignore, ignores things like cabal-dev and cabal sandboxes. does NOT ignores emacs and vim swap files

From the few repositories I've looked at above, it seems like all of them have a .gitignore, most of them ignore cabal-dev and cabal sandboxses, and some of them ignore emacs and vim swap files.

**Comment by fumieval** [comment]
We'd better have `.gitignore` unless there is an extraordinarily tremendous reason. `.gitignore` is not a kind of shame or a blot; it is a reasonable convention for Git users.

**Comment by kazu-yamamoto** [comment]
Merged.

@cdepillabout Thank you for your contribution!

**Pull request merged**
