### PR TITLE
Export record labels and constructor of Database.Record.TH.NameConfig

### PR DESCRIPTION
**Pull request by igrep**
This change makes it possible to customize `NameConfig` from the default.

### CODE REVIEW

**Comment by khibino** [comment]
Thanks.

**Comment by khibino** [comment]
Sorry, I forgot and misunderstood.
Record fields of NameConfig had been already exported in past revisions.
https://github.com/khibino/haskell-relational-record/blob/3eacfb1/persistable-record/src/Database/Record/TH.hs#L57

So, I will revert this merge.

**Comment by igrep** [comment]
Sorry. I missed it.
But I wonder why GHC complained it was not exported...
Oh, I've found! `columnName`, which I want to overwrite, is not exported!
https://github.com/igrep/haskell-relational-record/blob/6dd502ab5cc1a49fcd7b06239b716a56c8ec4467/persistable-record/src/Database/Record/TH.hs#L117

**Comment by khibino** [comment]
Okay, I will fix to export `columnName'

**Pull request merged**
